[phases.setup]
nixPkgs = ['python311', 'pip']
aptPkgs = ['gcc', 'pkg-config']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Python Flask app build complete"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload --access-logfile - --error-logfile - app:app'

[variables]
PYTHONPATH = '/app'
